"""预置知名科学家画像数据库（30 位，四象限覆盖）

CSI: 认知风格指数 (-24 强深度型 ~ +24 强整合型)
RAI: 自主动机指数 (负值=受控, 正值=自主, 典型范围 -20 ~ +60)
Big Five: 1-5 分
"""

SCIENTISTS = [
    # ═══ 自主整合型（右上象限：CSI>0, RAI 高）═══
    {
        "name": "理查德·费曼",
        "name_en": "Richard Feynman",
        "field": "理论物理",
        "era": "1918–1988",
        "csi": 18,
        "rai": 55,
        "openness": 4.8,
        "conscientiousness": 2.8,
        "extraversion": 4.5,
        "agreeableness": 2.8,
        "neuroticism": 2.0,
        "signature": "以好奇心为核心驱动，用物理直觉跨越学科边界",
        "match_reason_template": "你们都倾向于跨领域整合，且科研动力以内在好奇心为主导",
    },
    {
        "name": "列奥纳多·达芬奇",
        "name_en": "Leonardo da Vinci",
        "field": "博学家（艺术/工程/解剖/光学）",
        "era": "1452–1519",
        "csi": 24,
        "rai": 52,
        "openness": 5.0,
        "conscientiousness": 2.2,
        "extraversion": 3.5,
        "agreeableness": 3.0,
        "neuroticism": 3.0,
        "signature": "极致跨领域探索者，在艺术与科学之间自由穿行",
        "match_reason_template": "你们都具有极强的跨领域好奇心，喜欢在不同领域间发现隐藏联系",
    },
    {
        "name": "赫伯特·西蒙",
        "name_en": "Herbert Simon",
        "field": "人工智能/认知科学/管理学",
        "era": "1916–2001",
        "csi": 20,
        "rai": 48,
        "openness": 4.7,
        "conscientiousness": 4.2,
        "extraversion": 3.8,
        "agreeableness": 3.5,
        "neuroticism": 2.0,
        "signature": "在多个学科建立理论框架的系统思想家",
        "match_reason_template": "你们都善于将不同领域的方法组装成系统性理论框架",
    },
    {
        "name": "钱学森",
        "name_en": "Qian Xuesen",
        "field": "航天工程/系统科学",
        "era": "1911–2009",
        "csi": 16,
        "rai": 45,
        "openness": 4.5,
        "conscientiousness": 4.5,
        "extraversion": 3.0,
        "agreeableness": 3.2,
        "neuroticism": 2.5,
        "signature": "从工程实践到系统论，连接具体与宏观",
        "match_reason_template": "你们都在保持工程深度的同时追求系统性的宏观理论建构",
    },
    {
        "name": "玛丽·居里",
        "name_en": "Marie Curie",
        "field": "放射化学/物理学",
        "era": "1867–1934",
        "csi": 10,
        "rai": 50,
        "openness": 4.3,
        "conscientiousness": 4.8,
        "extraversion": 2.5,
        "agreeableness": 3.5,
        "neuroticism": 3.0,
        "signature": "以极致的实验毅力推动跨物理-化学的新领域",
        "match_reason_template": "你们都兼具跨领域视野和强大的实验执行力",
    },
    {
        "name": "约翰·冯·诺依曼",
        "name_en": "John von Neumann",
        "field": "数学/计算机/博弈论/量子力学",
        "era": "1903–1957",
        "csi": 22,
        "rai": 42,
        "openness": 4.9,
        "conscientiousness": 3.5,
        "extraversion": 4.0,
        "agreeableness": 2.5,
        "neuroticism": 2.0,
        "signature": "在纯数学和应用之间自如切换的天才整合者",
        "match_reason_template": "你们都具备在理论与应用之间快速切换的整合能力",
    },
    {
        "name": "爱德华·威尔逊",
        "name_en": "E.O. Wilson",
        "field": "社会生物学/生态学",
        "era": "1929–2021",
        "csi": 14,
        "rai": 46,
        "openness": 4.6,
        "conscientiousness": 4.0,
        "extraversion": 3.5,
        "agreeableness": 3.8,
        "neuroticism": 2.5,
        "signature": "从蚂蚁行为到人类社会，用生物学框架整合社会现象",
        "match_reason_template": "你们都善于从具体的观察中提炼出更宏大的理论框架",
    },
    # ═══ 自主专精型（左上象限：CSI<0, RAI 高）═══
    {
        "name": "安德鲁·怀尔斯",
        "name_en": "Andrew Wiles",
        "field": "数论",
        "era": "1953–",
        "csi": -20,
        "rai": 56,
        "openness": 4.0,
        "conscientiousness": 4.8,
        "extraversion": 1.8,
        "agreeableness": 3.5,
        "neuroticism": 3.0,
        "signature": "用七年时间独自攻克费马大定理的极致深耕者",
        "match_reason_template": "你们都倾向于在一个问题上深耕到极致，且科研动力来自纯粹的内在热情",
    },
    {
        "name": "拉马努金",
        "name_en": "Srinivasa Ramanujan",
        "field": "纯数学",
        "era": "1887–1920",
        "csi": -18,
        "rai": 58,
        "openness": 4.5,
        "conscientiousness": 3.5,
        "extraversion": 1.5,
        "agreeableness": 4.0,
        "neuroticism": 3.5,
        "signature": "凭直觉深入数学核心，独创性极强的数学天才",
        "match_reason_template": "你们都拥有对核心问题的极强直觉和内在驱动的深耕精神",
    },
    {
        "name": "芭芭拉·麦克林托克",
        "name_en": "Barbara McClintock",
        "field": "细胞遗传学",
        "era": "1902–1992",
        "csi": -14,
        "rai": 54,
        "openness": 4.2,
        "conscientiousness": 4.5,
        "extraversion": 2.0,
        "agreeableness": 3.0,
        "neuroticism": 2.5,
        "signature": "在学界质疑中坚持独立研究转座子的先驱",
        "match_reason_template": "你们都具有在垂直领域深耕并坚持独立判断的特质",
    },
    {
        "name": "格里戈里·佩雷尔曼",
        "name_en": "Grigori Perelman",
        "field": "微分几何/拓扑学",
        "era": "1966–",
        "csi": -22,
        "rai": 60,
        "openness": 4.0,
        "conscientiousness": 4.2,
        "extraversion": 1.0,
        "agreeableness": 2.0,
        "neuroticism": 3.5,
        "signature": "证明庞加莱猜想后拒绝一切荣誉，纯粹到极致的数学家",
        "match_reason_template": "你们都以纯粹的学术追求为最高驱动，不受外部激励左右",
    },
    {
        "name": "桑提亚哥·拉蒙-卡哈尔",
        "name_en": "Santiago Ramón y Cajal",
        "field": "神经解剖学",
        "era": "1852–1934",
        "csi": -12,
        "rai": 48,
        "openness": 4.3,
        "conscientiousness": 4.8,
        "extraversion": 2.5,
        "agreeableness": 3.0,
        "neuroticism": 2.5,
        "signature": "用精密观察和手绘揭示神经元结构的现代神经科学之父",
        "match_reason_template": "你们都具备在细分领域中追求极致精确的专注力",
    },
    {
        "name": "埃米·诺特",
        "name_en": "Emmy Noether",
        "field": "抽象代数/理论物理",
        "era": "1882–1935",
        "csi": -10,
        "rai": 52,
        "openness": 4.4,
        "conscientiousness": 4.0,
        "extraversion": 2.8,
        "agreeableness": 4.2,
        "neuroticism": 2.0,
        "signature": "在抽象代数中发现深层对称性的数学家",
        "match_reason_template": "你们都倾向于在抽象层面深入挖掘，追求理论的内在统一",
    },
    # ═══ 策略整合型（右下象限：CSI>0, RAI 低/中）═══
    {
        "name": "托马斯·爱迪生",
        "name_en": "Thomas Edison",
        "field": "发明/工程",
        "era": "1847–1931",
        "csi": 16,
        "rai": 5,
        "openness": 4.0,
        "conscientiousness": 4.5,
        "extraversion": 4.0,
        "agreeableness": 2.0,
        "neuroticism": 2.5,
        "signature": "以商业目标驱动的系统化发明家",
        "match_reason_template": "你们都善于跨领域整合技术，且注重将研究转化为实际成果",
    },
    {
        "name": "弗朗西斯·克里克",
        "name_en": "Francis Crick",
        "field": "分子生物学/神经科学",
        "era": "1916–2004",
        "csi": 14,
        "rai": 20,
        "openness": 4.5,
        "conscientiousness": 3.8,
        "extraversion": 4.2,
        "agreeableness": 2.5,
        "neuroticism": 2.0,
        "signature": "从物理学转向生物学，发现 DNA 双螺旋的跨界者",
        "match_reason_template": "你们都具有从一个领域跨入另一个领域并产出突破性成果的能力",
    },
    {
        "name": "詹姆斯·沃森",
        "name_en": "James Watson",
        "field": "分子生物学",
        "era": "1928–",
        "csi": 10,
        "rai": 12,
        "openness": 3.8,
        "conscientiousness": 3.5,
        "extraversion": 4.0,
        "agreeableness": 2.0,
        "neuroticism": 3.0,
        "signature": "竞争意识强烈，善于抓住关键合作机会的科学家",
        "match_reason_template": "你们都善于识别关键问题并快速整合资源推进研究",
    },
    {
        "name": "蒂姆·伯纳斯-李",
        "name_en": "Tim Berners-Lee",
        "field": "计算机科学/万维网",
        "era": "1955–",
        "csi": 12,
        "rai": 15,
        "openness": 4.2,
        "conscientiousness": 4.0,
        "extraversion": 3.0,
        "agreeableness": 4.5,
        "neuroticism": 2.0,
        "signature": "将信息技术与社会需求连接的万维网发明者",
        "match_reason_template": "你们都善于将技术能力与更广泛的应用需求相连接",
    },
    # ═══ 策略专精型（左下象限：CSI<0, RAI 低/中）═══
    {
        "name": "克劳德·香农",
        "name_en": "Claude Shannon",
        "field": "信息论/电子工程",
        "era": "1916–2001",
        "csi": -8,
        "rai": 18,
        "openness": 4.2,
        "conscientiousness": 3.5,
        "extraversion": 2.5,
        "agreeableness": 3.5,
        "neuroticism": 2.0,
        "signature": "在信息理论这一精确领域建立基石的开创者",
        "match_reason_template": "你们都倾向于在精确定义的领域中建立坚实的理论基础",
    },
    {
        "name": "弗雷德里克·泰勒",
        "name_en": "Frederick Taylor",
        "field": "科学管理",
        "era": "1856–1915",
        "csi": -12,
        "rai": 0,
        "openness": 3.0,
        "conscientiousness": 4.8,
        "extraversion": 3.5,
        "agreeableness": 2.0,
        "neuroticism": 2.5,
        "signature": "将科学方法应用于管理的效率专家",
        "match_reason_template": "你们都注重将深度专业知识转化为可量化、可优化的系统",
    },
    {
        "name": "尼尔斯·玻尔",
        "name_en": "Niels Bohr",
        "field": "量子物理",
        "era": "1885–1962",
        "csi": -6,
        "rai": 22,
        "openness": 4.3,
        "conscientiousness": 4.0,
        "extraversion": 3.8,
        "agreeableness": 4.5,
        "neuroticism": 2.0,
        "signature": "在量子力学的哲学基础上深入钻研的思想家",
        "match_reason_template": "你们都善于在专业领域内从多角度深入思考核心问题",
    },
    {
        "name": "保罗·狄拉克",
        "name_en": "Paul Dirac",
        "field": "量子力学/数学物理",
        "era": "1902–1984",
        "csi": -16,
        "rai": 35,
        "openness": 4.0,
        "conscientiousness": 4.5,
        "extraversion": 1.2,
        "agreeableness": 3.0,
        "neuroticism": 2.5,
        "signature": "追求数学之美的极简主义理论物理学家",
        "match_reason_template": "你们都倾向于在理论工作中追求数学上的简洁与美感",
    },
    # ═══ 平衡型（CSI ≈ 0）═══
    {
        "name": "阿尔伯特·爱因斯坦",
        "name_en": "Albert Einstein",
        "field": "理论物理",
        "era": "1879–1955",
        "csi": 5,
        "rai": 52,
        "openness": 4.8,
        "conscientiousness": 3.2,
        "extraversion": 2.8,
        "agreeableness": 3.5,
        "neuroticism": 3.0,
        "signature": "用思想实验突破物理学边界的独立思考者",
        "match_reason_template": "你们都兼具深度专注和宏观视野，且保持高度的独立思考",
    },
    {
        "name": "查尔斯·达尔文",
        "name_en": "Charles Darwin",
        "field": "自然历史/进化生物学",
        "era": "1809–1882",
        "csi": 6,
        "rai": 44,
        "openness": 4.5,
        "conscientiousness": 4.2,
        "extraversion": 2.5,
        "agreeableness": 4.0,
        "neuroticism": 3.5,
        "signature": "以耐心的观察和大胆的理论改变人类对生命的理解",
        "match_reason_template": "你们都善于从大量细致观察中提炼出革命性的理论框架",
    },
    {
        "name": "薛定谔",
        "name_en": "Erwin Schrödinger",
        "field": "量子物理/生物物理",
        "era": "1887–1961",
        "csi": 4,
        "rai": 40,
        "openness": 4.6,
        "conscientiousness": 3.5,
        "extraversion": 3.2,
        "agreeableness": 3.0,
        "neuroticism": 3.0,
        "signature": "在物理和生物之间架桥的思想家",
        "match_reason_template": "你们都在深度物理思考和跨领域探索之间保持平衡",
    },
    {
        "name": "艾伦·图灵",
        "name_en": "Alan Turing",
        "field": "计算机科学/数学/密码学",
        "era": "1912–1954",
        "csi": 2,
        "rai": 46,
        "openness": 4.5,
        "conscientiousness": 3.8,
        "extraversion": 2.0,
        "agreeableness": 3.0,
        "neuroticism": 3.5,
        "signature": "从纯数学到实际密码破解，理论与实践的完美结合",
        "match_reason_template": "你们都能在理论深度和实际应用之间自如切换",
    },
    {
        "name": "罗莎琳德·富兰克林",
        "name_en": "Rosalind Franklin",
        "field": "X 射线晶体学/分子生物学",
        "era": "1920–1958",
        "csi": -4,
        "rai": 38,
        "openness": 3.8,
        "conscientiousness": 4.8,
        "extraversion": 2.2,
        "agreeableness": 2.8,
        "neuroticism": 3.0,
        "signature": "以精密实验技术揭示分子结构的严谨科学家",
        "match_reason_template": "你们都以极致的实验精确度和技术深度为核心优势",
    },
    {
        "name": "简·古道尔",
        "name_en": "Jane Goodall",
        "field": "灵长类动物学/行为生态学",
        "era": "1934–",
        "csi": 0,
        "rai": 42,
        "openness": 4.5,
        "conscientiousness": 4.5,
        "extraversion": 3.5,
        "agreeableness": 4.8,
        "neuroticism": 2.5,
        "signature": "以长期耐心观察改写了人类对灵长类的认知",
        "match_reason_template": "你们都具备长期沉浸式研究的耐心和对研究对象的深切共情",
    },
    {
        "name": "詹姆斯·麦克斯韦",
        "name_en": "James Clerk Maxwell",
        "field": "电磁学/统计力学",
        "era": "1831–1879",
        "csi": 8,
        "rai": 48,
        "openness": 4.7,
        "conscientiousness": 4.0,
        "extraversion": 2.8,
        "agreeableness": 4.0,
        "neuroticism": 2.0,
        "signature": "将电学、磁学和光学统一为电磁理论的整合者",
        "match_reason_template": "你们都善于发现看似不相关的现象之间的深层联系并加以统一",
    },
    {
        "name": "屠呦呦",
        "name_en": "Tu Youyou",
        "field": "药学/中医药学",
        "era": "1930–",
        "csi": -2,
        "rai": 36,
        "openness": 3.5,
        "conscientiousness": 4.8,
        "extraversion": 2.0,
        "agreeableness": 3.5,
        "neuroticism": 2.5,
        "signature": "从传统中医文献中提取青蒿素的坚韧研究者",
        "match_reason_template": "你们都具备在特定领域长期坚持并最终取得突破的韧性",
    },
]
